version: '3.8'

services:
    backend:
        build: ./agenta-backend
        container_name: agenta-backend-test
        environment:
            - MONGODB_URI=mongodb://username:password@mongo:27017/
            - REDIS_URL=redis://redis:6379/0
            - ENVIRONMENT=development
            - DATABASE_MODE=test
            - FEATURE_FLAG=oss
            - AGENTA_TEMPLATE_REPO=agentaai/templates_v2
            - POSTHOG_API_KEY=phc_hmVSxIjTW1REBHXgj2aw4HW9X6CXb6FzerBgP9XenC7
        volumes:
            - ./agenta-backend/agenta_backend:/app/agenta_backend
            - ./agenta-backend/tests:/app/tests
            - /var/run/docker.sock:/var/run/docker.sock
        command:
            [
                "uvicorn",
                "agenta_backend.main:app",
                "--host",
                "0.0.0.0",
                "--port",
                "8001",
                "--reload",
                "--log-level",
                "info"
            ]
        ports:
            - "8000:8001"
        depends_on:
            mongo:
                condition: service_healthy
        networks:
            - agenta-test-network

    agenta-web:
        build:
            context: ./agenta-web
            dockerfile: dev.Dockerfile
        volumes:
            - ./agenta-web/src:/app/src
            - ./agenta-web/public:/app/public
            - .nextjs_cache:/app/.next
        ports:
            - "3000:3000"
        networks:
            - agenta-test-network

    mongo:
        image: mongo:5.0
        environment:
            MONGO_INITDB_ROOT_USERNAME: username
            MONGO_INITDB_ROOT_PASSWORD: password
        ports:
            - "27017:27017"
        healthcheck:
            test: [ "CMD", "mongo", "--eval", "db.adminCommand('ping')" ]
            interval: 10s
            timeout: 10s
            retries: 20
        networks:
            - agenta-test-network

    redis:
        image: redis:latest
        networks:
            - agenta-test-network
        volumes:
            - redis_data:/data

networks:
    agenta-test-network:
        name: agenta-test-network

volumes:
    mongodb_data:
    redis_data:
